// Vulkan/GLSL compute shader
// author: Christian Suer (github: 'cyberchriz')

#version 450 core

// setup specialization constants
// in "main" use gl_WorkGroupSize.x / gl_WorkGroupSize.y / gl_WorkGroupSize.z to get the actual workgroup size
layout(local_size_x_id = 0, local_size_y_id = 1, local_size_z_id = 2) in;

// setup buffers
layout(set = 0, binding = 0) buffer H_buffer        {float H[];};
layout(set = 0, binding = 1) buffer v_k_buffer      {float v_k[];};
layout(set = 0, binding = 2) buffer Temp_y_buffer   {float Temp_y[];}; // shape: {current_size}
layout(set = 0, binding = 3) buffer Temp_w_buffer   {float Temp_w[];}; // shape: {current_size}
layout(set = 0, binding = 4) buffer Tau_k_buffer    {float Tau_k[];};  // single element

// setup push constants layout
layout(push_constant) uniform push_constants {
    uint start_offset;  // beginning of the current subproblem within H
    uint end_offset;    // end of the current subproblem within H
    uint size_H;        // full size of H (needed for correct indexing)
    float shift_alpha;
    float shift_beta;
    uint k;
};

// main function
void main() {
    uint row = gl_GlobalInvocationID.x; // relative indexing, referring to the subproblem (for the indexing within the full matrix H we need to add the start_offset)
    uint current_size = end_offset - start_offset; // size of the current subproblem

    if (row < current_size) {

        // Determine the size of the Householder vector for this iteration
        uint v_k_size = (k < current_size - 2) ? 3 : 2;

        // The vector w is part of the transformation P_k = I - tau * v * v^T,
        // which acts on subproblem rows k to k+v_k_size-1. The product w = H*v should
        // therefore only be non-zero in that same range of rows:

        if (row >= k && row < (k + v_k_size)) {
            float sum = 0.0;
            
            for (uint j = 0; j < v_k_size; j++) {
                if (start_offset + k + j < end_offset) { // bounds check in H
                    sum += H[(start_offset + row) * size_H + (start_offset + k + j)] * v_k[j];
                }
            }
            Temp_w[row] = sum;
        } else {
            // For all other rows, w must be zero to not corrupt the matrix
            // in the subsequent right-hand side multiplication:
            Temp_w[row] = 0.0f;
        }

        memoryBarrierBuffer(); 
        barrier();
    }
}