// Vulkan/GLSL compute shader
// author: Christian Suer (github: 'cyberchriz')

#version 450 core

// setup specialization constants
// in "main" use gl_WorkGroupSize.x / gl_WorkGroupSize.y / gl_WorkGroupSize.z to get the actual workgroup size
layout(local_size_x_id = 0, local_size_y_id = 1, local_size_z_id = 2) in;

// setup buffers
layout(set = 0, binding = 0) buffer H_buffer        {float H[];};                   // flat representation of shape {rows, rows}
layout(set = 0, binding = 1) buffer v_k_buffer      {float v_k[];};                 // elements 0-2 store v_k, element 3 is for tau_k
layout(set = 0, binding = 2) buffer Temp_y_buffer   {float Temp_y[];};              // shape: {current_size}
layout(set = 0, binding = 3) buffer Temp_w_buffer   {float Temp_w[];};              // shape: {current_size}
layout(set = 0, binding = 4) buffer Tau_k_buffer    {float Tau_k[];};               // single element

// setup push constants layout
layout(push_constant) uniform push_constants {
    uint start_offset;  // beginning of the current subproblem within H
    uint end_offset;    // end of the current subproblem within H
    uint size_H;        // full size of H (needed for correct indexing)
    float shift_alpha;
    float shift_beta;
    uint k;
};

// avoid NAN/INF
float valid(float value) {
    const float FLOAT_MAX = 3.40282347e+38;
    const float FLT_EPSILON = 1e-06; //or: 1.19209e-07;
    if (isnan(value)) { return 0.0f; }
    else if (isinf(value)) { return (value > 0.0f) ? FLOAT_MAX : -FLOAT_MAX; }
    else { return (abs(value) <= FLT_EPSILON) ? 0.0f : value; }
}

shared float tau_k;

// main function
void main() {
    
    // ==============================================================================================

    // relative indexing, referring to the subproblem (for the indexing within the full matrix H we need to add the start_offset):
    uint row = gl_GlobalInvocationID.x;
    uint col = gl_GlobalInvocationID.y;

    // load global tau_k into shared local memory (local thread[0][0])
    if (gl_LocalInvocationID.x == 0 && gl_LocalInvocationID.y == 0) {
        tau_k = Tau_k[0];     
    }
    memoryBarrierShared(); barrier();

    uint current_size = end_offset - start_offset; // size of the current subproblem
    
    if (row < current_size && col < current_size) {

        // Determine the size of the Householder vector for this iteration
        uint v_k_size = (k < current_size - 2) ? 3 : 2;

        if (row >= k && row < (k + v_k_size)) {

            // Calculate the index into the v_k vector
            uint v_k_index = row - k;

            // Perform the rank-1 update
            uint flat_index_H = (start_offset + row) * size_H + (start_offset + col);
            float old_h = H[flat_index_H];
            float delta = -tau_k * v_k[v_k_index] * Temp_y[col];
            H[flat_index_H] = valid(old_h + delta);

        }
    }
    memoryBarrierBuffer(); barrier();

    // ==============================================================================================
}

