// Vulkan/GLSL compute shader for LUP Decomposition
// author: Christian Suer (github: 'cyberchriz')

// this is a helper function for LU decomposition;
// it checks if a row swap is needed for the current row 'k'

#version 450 core
#extension GL_EXT_shader_atomic_float : require

// setup specialization constants
// in "main" use gl_WorkGroupSize.x / gl_WorkGroupSize.y / gl_WorkGroupSize.z to get the actual workgroup size
layout(local_size_x_id = 0, local_size_y_id = 1, local_size_z_id = 2) in;

// --- Buffers ---
layout(set = 0, binding = 0) buffer l_buffer    { float L[]; };     // Lower triangular matrix L
layout(set = 0, binding = 1) buffer u_buffer    { float U[]; };     // Upper triangular matrix U (initialized with source matrix)
layout(set = 0, binding = 2) buffer p_buffer    { float P[]; };     // Permutation vector P (stores final row indices)
                                                                    // note: the P matrix could be of type 'uint' instead of 'float',
                                                                    // but using floats is more convenient for the host application,
                                                                    // since data buffers of NGrid objects are always floats by design
layout(set = 0, binding = 3) buffer swap_data_buffer {float swap_data[];};  // element 0 stores the row to swap for the current row 'k', element 1 stores the number of swaps performed
                                                                    
// --- Push Constants ---
layout(push_constant) uniform push_constants {
    uint rows;
    uint cols;
    uint k;     // pivot iterator
};

// --- Main Function ---
void main() {
    uint row = gl_GlobalInvocationID.x;

    // initialize swap_count
    if (k == 0 && gl_LocalInvocationID.x == 0) {
        atomicExchange(swap_data[1], 0);
    }

    // initialize swap_row with current row k (done by local thread 0)
    if (gl_LocalInvocationID.x == 0) {
        while (swap_data[0] < k) {
            atomicExchange(swap_data[0], k);
        }
    }
    memoryBarrierBuffer(); barrier();

    if (row > k && row < rows) {
        // search for highest absolute value in column k (below row k)
        while (U[row * cols + k] > U[uint(swap_data[0]) * cols + k]) {
            atomicExchange(swap_data[0], row);
        }
    }
    memoryBarrierBuffer(); barrier();
}