// Vulkan/GLSL compute shader
// author: Christian Suer (github: 'cyberchriz')

#version 450

// setup specialization constants
// in "main" use gl_WorkGroupSize.x / gl_WorkGroupSize.y / gl_WorkGroupSize.z to get the actual workgroup size
layout(local_size_x_id = 0, local_size_y_id = 1, local_size_z_id = 2) in;

// setup buffers
layout(set = 0, binding = 0) buffer data_real_buffer { float data_real[]; };
layout(set = 0, binding = 1) buffer data_imag_buffer { float data_imag[]; };
layout(set = 0, binding = 2) buffer result_buffer { float result[]; };

// setup push constants layout
layout(push_constant) uniform push_constants {
    uint N;
};

// main function
void main() {
    uint idx = gl_GlobalInvocationID.x;

    if (idx < N) {
        
        float x = data_real[idx];
        float y = data_imag[idx];

        result[idx] = sqrt(x * x + y * y);

        // Memory barrier to ensure results are visible to other threads if needed
        memoryBarrierBuffer(); barrier();
    }
}