// Vulkan/GLSL compute shader
// author: Christian Suer (github: 'cyberchriz')

#version 450

// setup specialization constants
// in "main" use gl_WorkGroupSize.x / gl_WorkGroupSize.y / gl_WorkGroupSize.z to get the actual workgroup size
layout(local_size_x_id = 0, local_size_y_id = 1, local_size_z_id = 2) in;

// setup buffers
layout(set = 0, binding = 0) buffer data_buffer {float data[];};
layout(set = 0, binding = 1) buffer required_digits_buffer {float required_digits[];};
layout(set = 0, binding = 2) buffer make_scientific_buffer {float make_scientific[];};
layout(set = 0, binding = 3) buffer has_fractional_buffer {float has_fractional[];};

// setup push constants layout
layout(push_constant) uniform push_constants {
    uint N;
    uint fract_significant_digits;
};

// helper function to implement log10
float log10(float x) { return log(x) / log(10); }

// main function
void main() {
    uint idx = gl_GlobalInvocationID.x;
    if (idx < N) {
        
        float value = data[idx];
        

        if (isnan(value) || isinf(value)) {
            make_scientific[idx] = 0.0f;
            required_digits[idx] = 4;
            has_fractional[idx] = 0.0f;
        }


        else {
            // get value properties
            bool negative = value < 0;
            float abs_value = abs(value);
            uint int_digits = abs_value > 1.0 ? uint(ceil(log10(abs_value))) : 1;
            uint leading_zeros = abs_value < 1.0 && abs_value != 0 ? uint(ceil(-log10(abs_value)) - 1) : 0;
            has_fractional[idx] = float(abs_value - round(abs_value) != 0);
            memoryBarrierBuffer(); // to make sure 'has_fractional' is available later in the code

            // avoid printing '-0'
            if (value == 0.0f && value < 0.0f) {
                value = 0.0f;
                data[idx] = 0.0f;
                negative = false;
            }

            // calculate the required digits        
            uint digits = negative ? 1 : 0; // if value is negative: add 1 digit for the minus sign
            digits += int_digits;
            digits += leading_zeros;
            if (fract_significant_digits !=0 && bool(has_fractional[idx])) {
                digits += fract_significant_digits + 1; // add 1 digit for the decimal point
            }

            // check if scientific format is better
            uint sci_digits = 6; // this is the minimum to display sign, integer part, the letter 'e', the exponent sign and a 2-digit exponent
            if (fract_significant_digits != 0 && bool(has_fractional[idx])) {
                sci_digits += 1 + fract_significant_digits; // add 1 digit for the decimal point
            }

            // write final result to buffer
            if (sci_digits < digits) {
                make_scientific[idx] = 1.0f;
                required_digits[idx] = float(sci_digits);
            }
            else {
                make_scientific[idx] = 0.0f;
                required_digits[idx] = float(digits);
            }
        }
    }
}
