// Vulkan/GLSL compute shader
// author: Christian Suer (github: 'cyberchriz')

#version 450 core

// setup specialization constants
// in "main" use gl_WorkGroupSize.x / gl_WorkGroupSize.y / gl_WorkGroupSize.z to get the actual workgroup size
layout(local_size_x_id = 0, local_size_y_id = 1, local_size_z_id = 2) in;

// setup buffers
layout(set = 0, binding = 0) buffer data_buffer {float data[];};
layout(set = 0, binding = 1) buffer local_results_buffer {float local_result[];};

// setup push constants
layout(push_constant) uniform push_constants {
    uint N;
};

// avoid NAN/INF
float valid(float value) {
    const float FLOAT_MAX = 3.40282347e+38;
    const float FLT_EPSILON = 1e-07; //or: 1.19209e-07;
    if (isnan(value)) { return 0.0f; }
    else if (isinf(value)) { return (value > 0.0f) ? FLOAT_MAX : -FLOAT_MAX; }
    else { return (abs(value) <= FLT_EPSILON) ? 0.0f : value; }
}

// shared variables
shared float local_product[gl_WorkGroupSize.x];

// main function
void main() {

    if (gl_GlobalInvocationID.x < N) {
        
        // Local Reduction
        local_product[gl_LocalInvocationID.x] = data[gl_GlobalInvocationID.x];
        groupMemoryBarrier();
        barrier();

        for (uint stride = gl_WorkGroupSize.x / 2; stride > 0; stride /= 2) {
            if (gl_LocalInvocationID.x < stride && gl_GlobalInvocationID.x + stride < N) {

                float val = local_product[gl_LocalInvocationID.x] * local_product[gl_LocalInvocationID.x + stride];                
                local_product[gl_LocalInvocationID.x] = valid(val);
            }
            groupMemoryBarrier();
            barrier();
        }

        // store local sum into local_results_buffer
        if (gl_LocalInvocationID.x == 0) {
            local_result[gl_WorkGroupID.x] = local_product[0];
        }

        // this shader has no global reduction!
        // it has to be invoked several times, until N <= workgroup_size_x
    }
    memoryBarrierBuffer(); barrier();
}