// Vulkan/GLSL compute shader
// author: Christian Suer (github: 'cyberchriz')

#version 450

// setup specialization constants
// in "main" use gl_WorkGroupSize.x / gl_WorkGroupSize.y / gl_WorkGroupSize.z to get the actual workgroup size
layout(local_size_x_id = 0, local_size_y_id = 1, local_size_z_id = 2) in;

// setup buffers
layout(set = 0, binding = 0) buffer data_buffer {float data[];};
layout(set = 0, binding = 1) buffer result_buffer {float result[];};

// setup push constants layout
layout(push_constant) uniform push_constants {
    uint N;
};

// global variables
const float FLOAT_MAX = 3.40282347e+38;
const float FLT_EPSILON = 1e-07; //1.19209e-07;

// avoid NAN/INF
float valid(float value) {
    if (isnan(value)) {
        return 0.0f;
    }
    else if (isinf(value)) {
        if (value > 0.0f) {
            return FLOAT_MAX;   
        }
        else {
            return -FLOAT_MAX;
        }
    }
    else {
        if (abs(value) <= FLT_EPSILON) {
            return 0.0f;
        }
        else {
            return value;
        }
    }
}

// main function
void main() {
    uint idx = gl_GlobalInvocationID.x;
    if (idx < N) {
        float val = data[idx];
        result[idx] = valid(val);
    }
    memoryBarrierBuffer(); barrier();
}
