// Vulkan/GLSL compute shader
// author: Christian Suer (github: 'cyberchriz')

#version 450 core

// setup specialization constants
// in "main" use gl_WorkGroupSize.x / gl_WorkGroupSize.y / gl_WorkGroupSize.z to get the actual workgroup size
layout(local_size_x_id = 0, local_size_y_id = 1, local_size_z_id = 2) in;

// setup buffers
layout(set = 0, binding = 0) buffer data_buffer {float data[];};
layout(set = 0, binding = 1) buffer result_buffer {float result[];};

// setup push constants
layout(push_constant) uniform push_constants {
    uint N;
    float range_from;
    float range_to;
    float data_min;
    float data_max;
};

// main function
void main() {
    uint idx = gl_GlobalInvocationID.x;

    if (idx < N) {
        float old_range = data_max - data_min;
        float new_range = range_to - range_from;
        
        float normalized_value;

        if (old_range == 0.0) {
            // If all data points are the same, they can't be "stretched out" and therefore should all map to the center of the new range
            normalized_value = range_from + 0.5 * new_range;
        }
        else {
            // First, scale to the [0, 1] range
            float scaled_0_1 = (data[idx] - data_min) / old_range;
            
            // Then, scale to the new range and shift by range_from
            normalized_value = scaled_0_1 * new_range + range_from;
        }

        // Assign the final result to the output buffer
        result[idx] = normalized_value;
    }
    memoryBarrierBuffer(); barrier();
}