// Vulkan/GLSL compute shader
// author: Christian Suer (github: 'cyberchriz')

#version 450 core

// setup specialization constants
// in "main" use gl_WorkGroupSize.x / gl_WorkGroupSize.y / gl_WorkGroupSize.z to get the actual workgroup size
layout(local_size_x_id = 0, local_size_y_id = 1, local_size_z_id = 2) in;

// setup buffers
layout(set = 0, binding = 0) buffer data_buffer {float data[];};
layout(set = 0, binding = 1) buffer result_buffer {float result[];};

// setup push constants
layout(push_constant) uniform push_constants {
    uint N;
    float data_mean;
    float data_stdev;
    float z_score;
};

// main function
void main() {
    uint idx = gl_GlobalInvocationID.x;
    if (idx < N) {
        
        // shift to zero mean
        float normalized = data[idx] - data_mean;

        // compress to unit-variance
        if (data_stdev != 0) {
            normalized /= data_stdev;
        }

        // stretch by z-score
        normalized *= z_score;

        // assign to result
        result[idx] = normalized;
    }
    memoryBarrierBuffer(); barrier();
}