#ifndef VKCONTEXT_GRAPHICS_TEST_H
#define VKCONTEXT_GRAPHCIS_TEST_H

#include <vkcontext.h>

#if __has_include(<spirv_bin.h>)
#include <spirv_bin.h>				// source header for shader binaries (auto-generated by CMake + GLSL compiler (glslangValidator))
#else
#include <spirv_bin_precompiled.h>	// fallback include for spirv_bin.h if not found in the include path
#endif

void vkcontext_graphics_test() {

	// setup environment
	VulkanManager& manager = VulkanManager::get_singleton();
	Device& device = manager.get_device();
	Semaphore* semaphore = manager.get_timeline_semaphore(0, VK_PIPELINE_STAGE_2_VERTEX_SHADER_BIT | VK_PIPELINE_STAGE_2_FRAGMENT_SHADER_BIT, VK_PIPELINE_STAGE_2_VERTEX_SHADER_BIT | VK_PIPELINE_STAGE_2_FRAGMENT_SHADER_BIT);
	Surface& surface = manager.get_surface();
	VkSurfaceFormatKHR surface_format = device.select_surface_format(surface);

	// load mesh
	Mesh model(device, "resources/models/obj/Skull/12140_Skull_v3_L2.obj", semaphore); // object source: https://free3d.com/3d-model/skull-v3--785914.html

	// create entity from mesh
	Entity entity(model);

	// setup camera
	Camera camera({ 2.0f, 2.0f, 2.0f }, { 0.0f, 0.0f, 0.0f });

	glm::vec4 light_position = glm::vec4(1.0f, 1.0f, 1.0f, 0.0f); // A directional light from the top-right-front
	glm::vec4 view_position = glm::vec4(2.0f, 2.0f, 2.0f, 1.0f);

	// create pipeline dependencies
	RenderPass renderpass(device);
	SubPass subpass(renderpass);
	uint32_t color_attachment_id = renderpass.add_color_attachment(surface_format, VK_IMAGE_LAYOUT_PRESENT_SRC_KHR, VK_IMAGE_LAYOUT_PRESENT_SRC_KHR, VK_ATTACHMENT_LOAD_OP_CLEAR, VK_ATTACHMENT_STORE_OP_STORE);
	uint32_t depth_attachment_id = renderpass.add_attachment(AttachmentType::DEPTH_TYPE, VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL, VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL, VK_ATTACHMENT_LOAD_OP_CLEAR, VK_ATTACHMENT_STORE_OP_DONT_CARE);
	subpass.add_attachment_reference(color_attachment_id);
	subpass.add_attachment_reference(depth_attachment_id);
	uint32_t subpass_index = subpass.finalize(0, VK_PIPELINE_BIND_POINT_GRAPHICS);
	renderpass.finalize();

	VkExtent2D extent = { 1920, 1080 };
	DepthBuffer depth_buffer(device, VK_IMAGE_TYPE_2D, VkExtent3D({ extent.width, extent.height, 1 }), VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT);

	Swapchain swapchain(device, renderpass, surface, surface_format, VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT, depth_buffer, NULLOPT, extent);

	ShaderModule vertex_shader(device, VERTEX_SHADER_GENERIC_SPIRV_BIN, VERTEX_SHADER_GENERIC_SPIRV_BYTES);
	std::optional<ShaderModule> fragment_shader = std::make_optional<ShaderModule>(device, FRAGMENT_SHADER_GENERIC_SPIRV_BIN, FRAGMENT_SHADER_GENERIC_SPIRV_BYTES);

	DescriptorSetLayout set_layout(device);
	set_layout.add_binding(STORAGE_BUFFER_DESCRIPTOR, VK_SHADER_STAGE_ALL_GRAPHICS);
	set_layout.finalize();

	DescriptorSet set(device, set_layout, manager.get_descriptor_pool());
	set.bind_buffer(0, model.get_material_buffer());
	set.write();

	std::vector<VkClearValue> clear_values(2);
	clear_values[0].color = { {0.0f, 0.0f, 0.0f, 1.0f} };
	clear_values[1].depthStencil = { 1.0f, 0 };

	float blend_factors[4] = { 1.0f,1.0f,1.0f,1.0f };
	const auto color_blend_state = std::make_optional<ColorBlendState>(
		VK_BLEND_FACTOR_ZERO,
		VK_BLEND_FACTOR_ONE,
		VK_BLEND_OP_ADD,
		VK_BLEND_FACTOR_ZERO,
		VK_BLEND_FACTOR_ONE,
		VK_BLEND_OP_ADD,
		blend_factors
	);

	PushConstants constants(
		entity.get_model_matrix(),
		camera.get_view_matrix(),
		camera.get_projection_matrix(),
		light_position,
		view_position
	);
	size_t material_offset = constants.add_values(uint32_t(0)); // reserved for the submesh material index

	GraphicsPipelineLayout pipeline_layout(device, set_layout, constants);

	// create pipeline
	GraphicsPipeline pipeline(
		device,
		renderpass,
		subpass_index,
		pipeline_layout,
		vertex_shader,
		std::vector<VertexDescriptions>{ model.get_vertex_descriptions() },
		color_blend_state,
		fragment_shader
	);

	// acquire a graphics task
	Task& task = manager.get_graphics_task();

	// main render loop
	while (true) {
		// process events (TODO)

		// update scene (TODO)

		// render next frame
		uint32_t image_index = swapchain.acquire_next_image(*semaphore);
		CommandBuffer& cb = task.get_command_buffer();
		cb.begin_recording();
		cb.bind_pipeline(pipeline);
		cb.bind_descriptor_set(set, pipeline);
		cb.bind_mesh(model);
		cb.begin_renderpass(renderpass, swapchain.get_framebuffer(image_index), { 0,0 }, swapchain.get_extent(), clear_values);

		// Loop through each sub-mesh and issue a draw call (= draw vertices per sub-mesh)
		for (const auto& submesh : model.get_submeshes()) {
			constants.add_values(submesh.material_index, material_offset); // in-place overwrite
			cb.bind_push_constants(constants, pipeline);
			cb.draw_indexed(submesh.index_count, 1, submesh.first_index, submesh.vertex_offset, 0);
		}

		cb.end_renderpass();
		cb.end_recording();

		task.timeline_sync(*semaphore);
		task.submit();

		swapchain.present_rendered_image(*semaphore);
	}
}
#endif