#ifndef VKCONTEXT_GRAPHICS_TEST_H
#define VKCONTEXT_GRAPHCIS_TEST_H

#include <vkcontext.h>

#if __has_include(<spirv_bin.h>)
#include <spirv_bin.h>                 // source header for shader binaries (auto-generated by CMake + GLSL compiler (glslangValidator))
#else
#include <spirv_bin_precompiled.h>     // fallback include for spirv_bin.h if not found in the include path
#endif

void vkcontext_graphics_test_helmet() {

	Log::set_level(LEVEL_WARNING);

	// setup environment
	auto& manager = VulkanManager::get_singleton();
	Device& device = manager.get_device();
	Semaphore* tl_semaphore = manager.get_timeline_semaphore(0, VK_PIPELINE_STAGE_2_VERTEX_SHADER_BIT | VK_PIPELINE_STAGE_2_FRAGMENT_SHADER_BIT, VK_PIPELINE_STAGE_2_VERTEX_SHADER_BIT | VK_PIPELINE_STAGE_2_FRAGMENT_SHADER_BIT);
	Surface& surface = manager.get_surface();
	auto surface_format = device.select_surface_format(surface);

	// load model
	Mesh model(device, "resources/models/gltf/DamagedHelmet.glb", tl_semaphore, true, true); // source: Khronos Group

	// create scene
	VkExtent2D extent = { 1920, 1080 };
	Scene scene;
	uint32_t entity_id = scene.add_entity(&model, { 0.0f, 0.0f, 0.0f }, true);
	scene.get_active_camera().set_position({ 0.0f, 0.0f, 2.0f });
	scene.get_active_camera().set_world_up({ 0.0f, -1.0f, 0.0f });
	scene.get_active_camera().set_yaw(-90.0f);
	scene.get_active_camera().set_pitch(0.0f);
	scene.get_active_camera().set_aspect_ratio(extent);
	scene.get_active_camera().set_near_plane(0.01f);
	scene.get_active_camera().set_far_plane(200.0f);
	scene.set_ambient({ 0.1f, 0.1f, 0.1f });
	scene.set_exposure(1.0f);
	uint32_t light_id = scene.add_scene_light(
		LightType::SPOT_LIGHT,			// type
		glm::vec3(0.0f, -5.0f, 3.0f),	// Position
		glm::vec3{ 1.0f, 1.0f, 1.0f }	// Color
	);
	scene.get_scene_light(light_id).set_direction(glm::normalize(scene.get_entity(entity_id).get_position() - scene.get_scene_light(light_id).get_position()));
	scene.get_scene_light(light_id).set_intensity(100.0f);
	scene.get_scene_light(light_id).set_range(20.0f);
	scene.get_scene_light(light_id).set_cone_angle(0.78f, 1.57f); // angle units: radians

	// create pipeline dependencies
	RenderPass renderpass(device);
	SubPass subpass(renderpass);
	uint32_t color_attachment_id = renderpass.add_color_attachment(surface_format, VK_IMAGE_LAYOUT_UNDEFINED, VK_IMAGE_LAYOUT_PRESENT_SRC_KHR, VK_ATTACHMENT_LOAD_OP_CLEAR, VK_ATTACHMENT_STORE_OP_STORE);
	uint32_t depth_attachment_id = renderpass.add_attachment(AttachmentType::DEPTH_TYPE, VK_IMAGE_LAYOUT_UNDEFINED, VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL, VK_ATTACHMENT_LOAD_OP_CLEAR, VK_ATTACHMENT_STORE_OP_DONT_CARE);
	subpass.add_attachment_reference(color_attachment_id);
	subpass.add_attachment_reference(depth_attachment_id);
	uint32_t subpass_index = subpass.finalize(0, VK_PIPELINE_BIND_POINT_GRAPHICS);
	renderpass.finalize();

	DepthBuffer depth_buffer(device, extent, VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT);

	Swapchain swapchain(device, renderpass, surface, surface_format, VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT, depth_buffer, NULLOPT, extent);

	ShaderModule vertex_shader(device, VERTEX_SHADER_GENERIC_SPIRV_BIN, VERTEX_SHADER_GENERIC_SPIRV_BYTES);
	auto fragment_shader = std::make_optional<ShaderModule>(device, FRAGMENT_SHADER_GENERIC_SPIRV_BIN, FRAGMENT_SHADER_GENERIC_SPIRV_BYTES);

	DescriptorSetLayout set_layout(device);
	set_layout.add_bindings(3, STORAGE_BUFFER_DESCRIPTOR, VK_SHADER_STAGE_FRAGMENT_BIT);						// for materials, lights, scene Material texIDs
	set_layout.add_bindings(1, STORAGE_BUFFER_DESCRIPTOR, VK_SHADER_STAGE_VERTEX_BIT);							// for model matrices
	set_layout.add_bindings(1, COMBINED_IMAGE_SAMPLER_DESCRIPTOR, VK_SHADER_STAGE_FRAGMENT_BIT, MAX_TEXTURES);	// for textures
	set_layout.finalize();

	DescriptorSet set(device, set_layout, manager.get_descriptor_pool());
	set.bind_buffer(0, scene.get_unique_materials_buffer(tl_semaphore));
	set.bind_buffer(1, scene.get_lights_buffer(tl_semaphore));
	set.bind_buffer(2, scene.get_scene_texIDs_buffer(tl_semaphore));
	set.bind_buffer(3, scene.get_model_matrices_buffer(tl_semaphore));
	set.bind_textures(4, scene.get_textures());
	set.write();

	std::vector<VkClearValue> clear_values(2);
	clear_values[0].color = { {0.0f, 0.0f, 0.0f, 1.0f} };
	clear_values[1].depthStencil = { 1.0f, 0 };

	const auto opaque_color_blend_state = std::make_optional<ColorBlendState>(
		VK_BLEND_FACTOR_ONE,
		VK_BLEND_FACTOR_ZERO,
		VK_BLEND_OP_ADD,
		VK_BLEND_FACTOR_ONE,
		VK_BLEND_FACTOR_ZERO,
		VK_BLEND_OP_ADD
	);

	const auto alpha_color_blend_state = std::make_optional<ColorBlendState>(
		VK_BLEND_FACTOR_SRC_ALPHA,
		VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA,
		VK_BLEND_OP_ADD,
		VK_BLEND_FACTOR_SRC_ALPHA,
		VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA,
		VK_BLEND_OP_ADD
	);

	PushConstants constants;
	size_t view_matrix_offset = constants.add_values(scene.get_active_camera().get_view_matrix());
	size_t projection_offset = constants.add_values(scene.get_active_camera().get_projection_matrix());
	size_t camera_position_offset = constants.add_values(scene.get_active_camera().get_position());
	size_t material_offset = constants.add_values(uint32_t(0));
	size_t light_count_offset = constants.add_values(scene.get_visible_lights_count());
	size_t ambient_scene_color_offset = constants.add_values(scene.get_ambient());
	size_t exposure_offset = constants.add_values(scene.get_exposure());

	GraphicsPipelineLayout pipeline_layout(device, set_layout, constants);

	// create pipelines
	GraphicsPipeline opaque_pipeline(device, renderpass, subpass_index, pipeline_layout, vertex_shader, opaque_color_blend_state, fragment_shader);
	GraphicsPipeline alpha_pipeline(device, renderpass, subpass_index, pipeline_layout, vertex_shader, alpha_color_blend_state, fragment_shader);

	// acquire a graphics task
	Task& task = manager.get_graphics_task(__FUNCTION__);
	Semaphore& image_available_bin_semaphore = task.make_temp_binary_semaphore(VK_PIPELINE_STAGE_2_COLOR_ATTACHMENT_OUTPUT_BIT, VK_PIPELINE_STAGE_2_COLOR_ATTACHMENT_OUTPUT_BIT);
	Semaphore& render_finished_bin_semaphore = task.make_temp_binary_semaphore(VK_PIPELINE_STAGE_2_ALL_GRAPHICS_BIT, VK_PIPELINE_STAGE_2_ALL_GRAPHICS_BIT);

	// main render loop
	std::vector<Entity*> entities = scene.get_visible_entities();
	while (true) {
		Log::debug("===== MAIN RENDER LOOP: START OF NEXT LOOP ITERATION =====");

		// process events (TODO)

		// update scene (push constants updates via in-place overwrites)
		scene.get_entity(entity_id).rotate(glm::vec3(0.0f, 0.5f, 0.0f));
		constants.add_values(scene.get_active_camera().get_view_matrix(), view_matrix_offset);
		constants.add_values(scene.get_active_camera().get_projection_matrix(), projection_offset);
		set.bind_buffer(3, scene.get_model_matrices_buffer(tl_semaphore));
		set.write();

		// render next frame
		uint32_t image_index = swapchain.acquire_next_image(image_available_bin_semaphore);
		CommandBuffer& cb = task.get_command_buffer();
		cb.begin_recording();

		// Set dynamic state before starting render pass
		cb.set_viewport({ 0, 0 }, swapchain.get_extent());
		cb.set_scissor({ 0, 0 }, swapchain.get_extent());

		// bind shared resources
		cb.begin_renderpass(renderpass, swapchain.get_framebuffer(image_index), { 0,0 }, swapchain.get_extent(), clear_values);
		cb.bind_mesh(model);

		// for each entity loop over sub-meshes and issue a draw call (= draw vertices per sub-mesh)

		// 1. opaque pass
		cb.bind_descriptor_set(set, opaque_pipeline);
		cb.bind_pipeline(opaque_pipeline);
		for (uint32_t entity_index = 0; entity_index < entities.size(); entity_index++) {
			for (const auto& submesh : entities[entity_index]->get_mesh().get_submeshes()) {
				constants.add_values(submesh.scene_local_material_index, material_offset); // in-place overwrite
				scene.get_unique_materials()[submesh.scene_local_material_index]->ambient.w = AlphaMode::OPAQUE_MODE;
				scene.get_unique_materials()[submesh.scene_local_material_index]->base_color.a = 1.0f;
				cb.bind_push_constants(constants, opaque_pipeline);
				cb.draw_indexed(submesh.index_count, 1, submesh.first_index, submesh.vertex_offset, entity_index);
			}
		}

		// 2. transparency pass
		cb.bind_descriptor_set(set, alpha_pipeline);
		cb.bind_pipeline(alpha_pipeline);
		for (uint32_t entity_index = 0; entity_index < entities.size(); entity_index++) {
			for (const auto& submesh : entities[entity_index]->get_mesh().get_submeshes()) {
				constants.add_values(submesh.scene_local_material_index, material_offset); // in-place overwrite
				scene.get_unique_materials()[submesh.scene_local_material_index]->ambient.w = AlphaMode::BLEND_MODE;
				scene.get_unique_materials()[submesh.scene_local_material_index]->base_color.a = 0.5f;
				cb.bind_push_constants(constants, alpha_pipeline);
				cb.draw_indexed(submesh.index_count, 1, submesh.first_index, submesh.vertex_offset, entity_index);
			}
		}

		cb.end_renderpass();
		cb.end_recording();

		task.timeline_sync(*tl_semaphore);
		task.wait_binary_semaphore(image_available_bin_semaphore);
		task.signal_binary_semaphore(render_finished_bin_semaphore);
		task.submit();

		swapchain.present_rendered_image(render_finished_bin_semaphore);

		task.get_fence().wait(__FUNCTION__);
		task.get_fence().reset(__FUNCTION__);
		task.clear_semaphore_list();
	}
}
#endif
