import sys, os

# Arguments: [1] SPV_PATH, [2] CPP_PATH, [3] VAR_NAME
SPV_PATH = sys.argv[1]
CPP_PATH = sys.argv[2]
VAR_NAME = sys.argv[3]

# Ensure the output directory exists
os.makedirs(os.path.dirname(CPP_PATH), exist_ok=True)

try:
    with open(SPV_PATH, 'rb') as f_in:
        data = f_in.read()
except FileNotFoundError:
    print(f'Error: SPIR-V file not found: {SPV_PATH}', file=sys.stderr)
    sys.exit(1)

with open(CPP_PATH, 'w') as f_out:
    # Write the C++ header and array definition
    f_out.write('// Generated by CMake/Python. Do not edit.\n')
    f_out.write('#include <cstddef>\n')
    f_out.write('#include <cstdint>\n')
    f_out.write(f'extern "C" __declspec(align(16)) const unsigned char {VAR_NAME}_SPIRV_BIN[] = {{\n    ')
    
    # Write hex literals (25 bytes per line for readability)
    hex_data = [f'0x{byte:02x}' for byte in data]
    lines = [', '.join(hex_data[i:i + 25]) for i in range(0, len(hex_data), 25)]
    f_out.write(',\n    '.join(lines))
    
    # Write array closing and size definition
    f_out.write('\n};\n') # FIX: Closing the array with }; and not }}; (was double brace)
    f_out.write(f'extern "C" const size_t {VAR_NAME}_SPIRV_BYTES = sizeof({VAR_NAME}_SPIRV_BIN);\n')